spring.config.import=optional:file:.env[.properties]
spring.application.name=backend

# ---- JWT ----
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ---- Gemini ----
gemini.api-key=${GEMINI_API_KEY}

# ---- CORS ----
cors.allowed-origins=${CORS_ORIGINS}

# ---- Server ----
server.port=${PORT}

spring.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@travelwisecluster.2jbt20z.mongodb.net/demo?retryWrites=true&w=majority